#import "../../lib.typ":*

= Free Fields at Finite Temperature

== The Imaginary-Time Formalism

Chapter 2 constructed free fields in the vacuum and ended with their
Euclidean propagators on an infinite time axis.  A system in thermal
equilibrium is described by a different state, not by different local field
equations.  The central object is now a trace over the Hilbert space.  That
trace identifies the two ends of Euclidean time and turns the line into a
circle.  Finite-temperature field theory begins with this change of global
geometry.

Throughout this chapter we use the natural-unit convention $k_B=1$ and write

$
  beta:=1/T,
$ <eq:inverse-temperature-definition>

where $T>0$ is the temperature.  The symbol $T_tau$ below denotes imaginary-
time ordering and is unrelated to the temperature.

=== Thermal ensembles and the preferred rest frame

Let $hat(H)$ be the Hamiltonian in the rest frame of the heat bath.  The
canonical partition function and normalized density operator are

$
  Z_beta
  :=upright("Tr") e^(-beta hat(H)),
  quad
  hat(rho)_beta
  :=e^(-beta hat(H))/Z_beta.
$ <eq:canonical-thermal-state>

The thermal expectation value of an operator $hat(cal(O))$ is therefore

$
  chevron.l hat(cal(O)) chevron.r_beta
  :=upright("Tr") [hat(rho)_beta hat(cal(O))]
  =1/Z_beta upright("Tr")
    [e^(-beta hat(H)) hat(cal(O))].
$ <eq:thermal-expectation-value>

Unlike the vacuum, a thermal state selects a timelike four-velocity.  In the
rest frame it distinguishes time translations generated by $hat(H)$ from
spatial translations.  A homogeneous and isotropic equilibrium state remains
invariant under spatial translations and rotations, but not under Lorentz
boosts.  This is why thermal propagators will depend separately on a temporal
frequency and on $bold(p)$, even though the microscopic action remains
Lorentz invariant.

For an operator with no explicit time dependence, define its imaginary-time
Heisenberg evolution by

$
  hat(cal(O)) (tau)
  :=e^(tau hat(H)) hat(cal(O)) e^(-tau hat(H)),
  quad
  0<=tau<beta.
$ <eq:imaginary-time-heisenberg-evolution>

This is the analytic continuation $t=-i tau$ of ordinary Heisenberg
evolution.  It is not unitary evolution: imaginary time organizes the thermal
weight rather than describing a real-time experiment.

=== The thermal trace closes Euclidean time

Consider first a real scalar field.  Insert a complete set of field
eigenstates into the trace in @eq:canonical-thermal-state:

$
  Z_beta
  =integral cal(D) phi_0
    bra(phi_0) e^(-beta hat(H)) ket(phi_0).
$ <eq:thermal-trace-field-basis>

Time slicing the matrix element gives the same Euclidean construction as in
Chapter 1, but the field at the final slice is now identified with the field
at the initial slice.  Consequently,

$
  Z_beta
  =integral_(phi (beta,bold(x))=phi (0,bold(x)))
    cal(D) phi e^(-S_(E,beta) [phi]),
$ <eq:bosonic-thermal-path-integral>

where, for the free scalar,

$
  S_(E,beta) [phi]
  :=integral_0^beta dd(tau) integral dd(x,[3])
    [
      1/2 (partial_tau phi)^2
      +1/2 (bold(nabla) phi)^2
      +1/2 m^2 phi^2
    ].
$ <eq:thermal-scalar-euclidean-action>

The action is Euclidean: with the fixed rotation $t=-i tau$, the Minkowski
weight $e^(i S_M)$ has become $e^(-S_E)$.  The endpoint condition in
@eq:bosonic-thermal-path-integral is more important than the choice of
coordinates used to display it.  It says that a bosonic thermal field lives
on

$
  cal(M)_(E,beta)=S_beta^1 times RR^3,
  quad
  phi (tau+beta,bold(x))=phi (tau,bold(x)),
$ <eq:bosonic-thermal-circle>

where the Euclidean-time circle $S_beta^1$ has circumference $beta$.  The
compactification comes from the trace, not from the Wick rotation alone.
At zero temperature the circle opens into the infinite Euclidean time axis.

For fermions the trace must instead be evaluated with the coherent states of
Chapter 1.  The minus sign in the coherent-state trace gives

$
  Psi (tau+beta,bold(x))&=-Psi (tau,bold(x)), \
  overline(Psi) (tau+beta,bold(x))
    &=-overline(Psi) (tau,bold(x)).
$ <eq:fermionic-thermal-circle>

Thus bosonic integration variables are periodic and fermionic integration
variables are antiperiodic around the thermal circle.  This agrees with
@eq:fermionic-antiperiodic-boundary and follows from statistics and the trace,
not from the free equations of motion.  It therefore remains true in an
interacting theory.

=== Imaginary-time ordering and the KMS condition

Thermal Euclidean correlators are expectation values ordered around the
circle.  For two operators define

$
  cal(G)_(A B,beta) (tau)
  :=chevron.l T_tau hat(A) (tau)hat(B) (0) chevron.r_beta.
$ <eq:thermal-imaginary-time-two-point-function>

The ordering symbol places the operator with larger $tau$ to the left.  Each
exchange of two Grassmann-odd operators contributes a minus sign, exactly as
for the vacuum time ordering used in Chapter 2.  For $0<tau<beta$, no exchange
is required and

$
  cal(G)_(A B,beta) (tau)
  =1/Z_beta upright("Tr")
    [e^(-beta hat(H))hat(A) (tau)hat(B) (0)].
$ <eq:thermal-two-point-trace>

Cyclicity of the trace moves $hat(A)$ once around the thermal circle and gives

$
  chevron.l hat(A) (tau)hat(B) (0) chevron.r_beta
  =chevron.l hat(B) (0)hat(A) (tau-beta) chevron.r_beta.
$ <eq:kms-condition-imaginary-time>

This is the imaginary-time Kubo--Martin--Schwinger, or KMS, condition.  The
trace identity itself has no statistical sign.  The sign appears when the
operators are put back into imaginary-time order.  If $hat(A)$ and $hat(B)$
are both bosonic, or both fermionic, their ordered two-point function obeys

$
  cal(G)_(A B,beta) (tau+beta)
  =zeta_A cal(G)_(A B,beta) (tau),
  quad
  zeta_A=+1 " for bosons",
  quad
  zeta_A=-1 " for fermions".
$ <eq:thermal-correlator-boundary-condition>

The path-integral boundary conditions in @eq:bosonic-thermal-circle and
@eq:fermionic-thermal-circle and the operator KMS condition are therefore two
descriptions of the same thermal trace.  The former is convenient for
Gaussian integration; the latter remains meaningful without choosing a field
basis and is the intrinsic characterization of thermal equilibrium.

Because the time coordinate lies on a circle, only separations modulo $beta$
are independent.  One may take $0<=tau<beta$ as a fundamental interval and
use @eq:thermal-correlator-boundary-condition to extend a correlator outside
it.  Discontinuities of a correlator or of its imaginary-time derivatives at
coincident times encode canonical commutators or anticommutators and will be
visible when the free propagators are constructed below.

=== Generating functionals on the thermal circle

The Gaussian machinery of Chapters 1 and 2 carries over after changing the
integration domain and boundary conditions.  Write
$X:=(tau,bold(x))$ and introduce a periodic source $J (X)$ for a real scalar.
The normalized thermal generating functional is

$
  cal(Z)_beta [J]
  :=frac(
    integral_("periodic") cal(D) phi
      exp[-S_(E,beta) [phi]
        +integral_0^beta dd(tau) integral dd(x,[3])
          J (X)phi (X)],
    integral_("periodic") cal(D) phi
      e^(-S_(E,beta) [phi])
  ).
$ <eq:normalized-thermal-generating-functional>

The denominator is the unnormalized partition function $Z_beta$, up to the
field-independent normalization inherited from the regulated measure.  It
must be retained when computing thermodynamic potentials, whereas it cancels
from normalized correlators.  Functional derivatives generate
imaginary-time-ordered thermal Green functions:

$
  G_(E,beta)^((n)) (X_1,dots,X_n)
  :=chevron.l
    T_tau phi (X_1)dots phi (X_n)
    chevron.r_beta
  =[
    (delta^n cal(Z)_beta [J])/
    (delta J (X_1)dots delta J (X_n))
  ]_(J=0).
$ <eq:thermal-correlators-from-source>

A complex scalar uses two independent periodic commuting sources.  A Dirac
field uses independent antiperiodic Grassmann sources $eta$ and
$overline(eta)$, coupled in the fixed order
$overline(eta)Psi+overline(Psi)eta$.  Apart from these boundary conditions,
the source-derivative conventions and Gaussian identities are exactly those
of @eq:euclidean-generating-functional-definition and
@eq:free-dirac-master-functional.

For a free real scalar, writing $cal(K)_(E,beta)$ for the quadratic operator
acting on periodic fields gives the same formal answer as at zero
temperature,

$
  cal(Z)_(0,beta) [J]
  =exp[
    1/2 integral_0^beta dd(tau_x) integral_0^beta dd(tau_y)
      integral dd(x,[3])dd(y,[3])
      J (X)G_beta (X-Y)J (Y)
  ],
  quad
  G_beta=cal(K)_(E,beta)^(-1).
$ <eq:free-thermal-scalar-master-functional>

The notation $cal(K)_(E,beta)^(-1)$ means the inverse on the space of
periodic functions.  This domain is part of the definition of the inverse:
the local differential operator is the same as at zero temperature, but its
Green function changes when the allowed boundary conditions change.  Section
3.2 will diagonalize this inverse using Fourier modes around the circle.

=== Thermodynamics and the zero-temperature limit

The unnormalized trace contains the equilibrium thermodynamics.  In a
spatial volume $V$, the Helmholtz free energy, mean energy, and pressure of a
homogeneous system are

$
  F_beta&=-1/beta log Z_beta, \
  E_beta&=-(partial log Z_beta)/(partial beta), \
  p_beta&=1/(beta V) log Z_beta.
$ <eq:thermodynamic-derivatives-of-partition-function>

The pressure formula assumes the thermodynamic limit and fixed temperature.
An additive vacuum energy contributes a factor $e^(-beta E_0)$ to $Z_beta$;
it cancels from normalized correlators but must be subtracted or otherwise
specified when an absolute free energy is quoted.

If the ground state is unique, then as $beta arrow.r infinity$ the normalized
thermal trace projects onto it:

$
  lim_(beta arrow.r infinity)
    chevron.l hat(cal(O)) chevron.r_beta
  =mel(0,hat(cal(O)),0).
$ <eq:zero-temperature-thermal-limit>

At the same time, $S_beta^1 times RR^3$ opens into $RR^4$, and the thermal
propagators approach the Euclidean vacuum propagators summarized in
@eq:free-euclidean-propagator-summary.  Finite temperature has therefore not
changed the local free kernels.  It has changed the state, compactified
Euclidean time, and restricted the functions on which those kernels are
inverted.  The discrete frequencies associated with those restrictions are
the subject of the next section.

== Matsubara Frequencies

Section 3.1 reduced finite-temperature kinematics to a boundary-value
problem on the Euclidean-time circle.  We now diagonalize translations around
that circle.  The allowed temporal frequencies are discrete, while spatial
momentum becomes continuous in the thermodynamic limit.  Keeping both
directions discrete at first makes every normalization factor and every delta
function unambiguous.

=== Fourier modes in a finite thermal box

Temporarily place the system in a cubic spatial box of side $L$ and volume
$V=L^3$, with periodic spatial boundary conditions.  Take the fundamental
domain to be

$
  0<=tau<beta,
  quad
  0<=x_i<L,
$ <eq:finite-thermal-box-domain>

so an endpoint is never counted twice.  Spatial plane waves then have

$
  bold(p)_bold(k):=(2 pi)/L bold(k),
  quad
  bold(k) in ZZ^3.
$ <eq:finite-box-spatial-momenta>

For the temporal direction, let $s=B$ denote a periodic bosonic function and
$s=F$ an antiperiodic fermionic function.  Write their boundary conditions as

$
  f_s (tau+beta,bold(x))
  =zeta_s f_s (tau,bold(x)),
  quad
  zeta_B=+1,
  quad
  zeta_F=-1.
$ <eq:unified-thermal-boundary-condition>

A temporal plane wave $e^(i omega tau)$ belongs to this function space only
when $e^(i omega beta)=zeta_s$.  Hence

$
  omega_n^B&=(2 pi n)/beta=2 pi n T, \
  omega_n^F&=((2n+1) pi)/beta=(2n+1) pi T,
  quad n in ZZ.
$ <eq:bosonic-fermionic-matsubara-frequencies>

The integer $n$ labels a point on a frequency lattice.  In particular,
$omega_0^F=pi T$ is not a zero frequency.  The normalized plane-wave basis on
the finite thermal box is

$
  u_(n bold(k))^((s)) (X)
  :=1/sqrt(beta V)
    e^(i omega_n^s tau+i bold(p)_bold(k) dot bold(x)),
  quad
  X:=(tau,bold(x)).
$ <eq:normalized-thermal-plane-wave-basis>

Within either boundary-condition sector, the temporal frequency differences
are integer multiples of $2 pi/beta$.  Combining temporal and spatial
orthogonality therefore gives

$
  integral_0^beta dd(tau) integral_V dd(x,[3])
    [u_(n bold(k))^((s)) (X)]^*
    u_(m bold(l))^((s)) (X)
  =delta_(n m) delta_(bold(k) bold(l)).
$ <eq:finite-thermal-box-orthogonality>

Bosonic and fermionic modes are not two subsets of one orthogonal basis.
They belong to different function spaces, so
@eq:finite-thermal-box-orthogonality is to be used with the same value of $s$
on both factors.  Every field in that sector has the expansion

$
  f_s (X)
  &=sum_(n in ZZ) sum_(bold(k) in ZZ^3)
    u_(n bold(k))^((s)) (X) f_(n bold(k))^s, \
  f_(n bold(k))^s
  &=integral_0^beta dd(tau) integral_V dd(x,[3])
    [u_(n bold(k))^((s)) (X)]^* f_s (X).
$ <eq:finite-thermal-box-fourier-transform>

These equations are ordinary Fourier series in four compact directions.  No
continuum delta function has yet appeared.

=== Completeness and thermal delta functions

Completeness of the basis means

$
  sum_(n in ZZ) sum_(bold(k) in ZZ^3)
    u_(n bold(k))^((s)) (X)
    [u_(n bold(k))^((s)) (Y)]^*
  =delta_beta^s (tau_x-tau_y)
    delta_V^((3)) (bold(x)-bold(y)),
$ <eq:finite-thermal-box-completeness>

where the temporal and spatial kernels are

$
  delta_beta^s (tau)
  &:=1/beta sum_(n in ZZ) e^(i omega_n^s tau), \
  delta_V^((3)) (bold(x))
  &:=1/V sum_(bold(k) in ZZ^3)
    e^(i bold(p)_bold(k) dot bold(x)).
$ <eq:thermal-and-spatial-periodic-deltas>

The spatial kernel is the periodic delta function in the box.  The two
temporal kernels can be displayed as image sums on the covering line:

$
  delta_beta^B (tau)
  &=sum_(r in ZZ) delta (tau-r beta), \
  delta_beta^F (tau)
  &=sum_(r in ZZ) (-1)^r delta (tau-r beta).
$ <eq:bosonic-fermionic-delta-image-sums>

Thus $delta_beta^B (tau+beta)=delta_beta^B (tau)$, whereas
$delta_beta^F (tau+beta)=-delta_beta^F (tau)$.  The latter is not an ordinary
periodic delta function; it is the identity kernel on the antiperiodic
function space.  More precisely, for $X$ in the half-open fundamental domain,

$
  integral_0^beta dd(tau_y) integral_V dd(y,[3])
    delta_beta^s (tau_x-tau_y)
    delta_V^((3)) (bold(x)-bold(y)) f_s (Y)
  =f_s (X).
$ <eq:thermal-delta-reproducing-property>

Equations @eq:finite-thermal-box-orthogonality and
@eq:finite-thermal-box-completeness are complementary.  Orthogonality extracts
a mode coefficient; completeness reconstructs a function and fixes the delta
kernel that appears when a differential operator acts on its Green function.

=== The thermodynamic limit and sum-integrals

Now take $L arrow.r infinity$ while keeping $T$ fixed.  The spatial momentum
lattice becomes dense and

$
  1/V sum_(bold(k) in ZZ^3)
  arrow.r integral (dd(p,[3]))/((2 pi)^3)
  =:integral_bold(p).
$ <eq:spatial-thermodynamic-limit>

The compact time direction remains discrete.  Define the Euclidean thermal
four-momentum and its contraction with position by

$
  P_s&:=(omega_n^s,bold(p)), \
  P_s dot X&:=omega_n^s tau+bold(p) dot bold(x), \
  P_s^2&:=(omega_n^s)^2+bold(p)^2.
$ <eq:euclidean-thermal-four-momentum>

The label $s$ records which frequency lattice is being summed.  We reserve
the following symbols for bosonic and fermionic sum-integrals:

$
  integral_(P_B) F (P_B)
  &:=T sum_(n in ZZ) integral_bold(p)
    F (omega_n^B,bold(p)), \
  integral_(P_F) F (P_F)
  &:=T sum_(n in ZZ) integral_bold(p)
    F (omega_n^F,bold(p)).
$ <eq:bosonic-fermionic-sum-integrals>

The subscript $P_B$ or $P_F$ is part of the notation and must not be omitted
when the boundary-condition sector is ambiguous.  With these conventions,
the Fourier transform used in calculations is

$
  f_s (X)
  &=integral_(P_s) e^(i P_s dot X) f_s (P_s), \
  f_s (P_s)
  &=integral_0^beta dd(tau) integral dd(x,[3])
    e^(-i P_s dot X) f_s (X).
$ <eq:thermal-fourier-transform-continuum-space>

For a real periodic scalar,
$phi (P_B)^*=phi (-P_B)$, where
$-P_B=(-omega_n^B,-bold(p))$ corresponds to replacing $n$ by $-n$.
The spatial continuum orthogonality relation is

$
  integral_0^beta dd(tau) integral dd(x,[3])
    e^(i (P_s-Q_s) dot X)
  =beta delta_(n m) (2 pi)^3
    delta^((3)) (bold(p)-bold(q)),
$ <eq:thermal-plane-wave-orthogonality-continuum-space>

where $P_s=(omega_n^s,bold(p))$ and
$Q_s=(omega_m^s,bold(q))$ belong to the same sector.  Completeness becomes

$
  integral_(P_s) e^(i P_s dot (X-Y))
  =delta_beta^s (tau_x-tau_y)
    delta^((3)) (bold(x)-bold(y)).
$ <eq:thermal-plane-wave-completeness-continuum-space>

The factor $T=1/beta$ in the sum-integral is therefore forced by
completeness.  Omitting it would produce $beta delta_beta^s$ instead of the
identity kernel.

The Fourier convention also turns derivatives into multiplication:

$
  partial_tau&arrow.r i omega_n^s, \
  bold(nabla)&arrow.r i bold(p), \
  -partial_tau^2-bold(nabla)^2&arrow.r P_s^2.
$ <eq:thermal-fourier-derivative-rules>

This is the promised diagonalization of the Euclidean kinetic operators.  We
will invert the field-specific scalar, Dirac, and gauge kernels only in
Sections 3.3--3.5.

=== Frequency bookkeeping and zero modes

Products of thermal fields inherit the product of their boundary signs.
Thus a boson times a boson and a fermion times a fermion are periodic, while a
boson times a fermion is antiperiodic.  On the frequency lattices this becomes

$
  omega_n^B+omega_m^B&=omega_(n+m)^B, \
  omega_n^F+omega_m^B&=omega_(n+m)^F, \
  omega_n^F-omega_m^F&=omega_(n-m)^B, \
  omega_n^F+omega_m^F&=omega_(n+m+1)^B.
$ <eq:matsubara-frequency-bookkeeping>

These identities are the thermal version of energy bookkeeping.  If a
product of plane waves is periodic around the circle, its total frequency is
bosonic.  Define

$
  Omega:=sum_(a=1)^r omega_a,
  quad
  N_Omega:=(beta Omega)/(2 pi) in ZZ.
$ <eq:total-matsubara-frequency-index>

Integration over one period then gives

$
  integral_0^beta dd(tau) integral dd(x,[3])
    e^(i Omega tau+i sum_(a=1)^r bold(p)_a dot bold(x))
  =beta (2 pi)^3
    delta_(N_Omega 0)
    delta^((3)) (sum_(a=1)^r bold(p)_a).
$ <eq:thermal-frequency-momentum-conservation>

The temporal delta in @eq:thermal-frequency-momentum-conservation is a
Kronecker delta on the integer frequency index.  Incoming and outgoing
momenta are represented by the signs included in $omega_a$ and $bold(p)_a$.
A local action term is Grassmann even; in the ordinary boson--fermion sectors
it therefore contains an even number of fermionic fields, so its integrand is
periodic and this conservation rule applies.

There is a qualitative difference at the origin of the two lattices:

$
  omega_0^B=0,
  quad
  abs(omega_n^F)>=pi T>0.
$ <eq:bosonic-zero-mode-fermionic-gap>

Bosonic fields therefore contain a time-independent Matsubara mode, while
fermionic fields do not.  The bosonic zero mode often controls long-distance
thermal physics and is the source of infrared sensitivity in later chapters.
Here it is simply a distinguished basis vector; no resummation or effective
description is needed yet.

=== Recovering continuous Euclidean frequency

Both Matsubara lattices have spacing
$Delta omega=2 pi T$.  For a sufficiently regular function that decays at
large frequency,

$
  T sum_(n in ZZ) F (omega_n^s)
  =1/(2 pi) sum_(n in ZZ)
    Delta omega F (omega_n^s)
  arrow.r integral_( -infinity)^infinity
    (dd(p_4))/(2 pi) F (p_4)
$ <eq:zero-temperature-matsubara-limit>

as $T arrow.r 0$, or equivalently $beta arrow.r infinity$.  The half-step
offset of the fermionic lattice becomes irrelevant when the spacing tends to
zero.  Consequently,

$
  integral_(P_B) F (P_B)
  &arrow.r integral (dd(p_E,[4]))/((2 pi)^4) F (p_E), \
  integral_(P_F) F (P_F)
  &arrow.r integral (dd(p_E,[4]))/((2 pi)^4) F (p_E).
$ <eq:zero-temperature-sum-integral-limit>

At the same time $delta_beta^s (tau)$ approaches the ordinary delta function
on the line, and @eq:thermal-fourier-transform-continuum-space becomes the
zero-temperature Euclidean transform used at the end of Chapter 2.

The Matsubara frequency is an eigenvalue of $-i partial_tau$, not a directly
measured Minkowski energy.  Analytic continuation to real-time Green
functions must be performed on a function of complex frequency after its
Matsubara data have been organized; it is not an extra replacement inside the
Fourier series.  For the rest of this chapter, the Euclidean label $P_B$ or
$P_F$ will keep that distinction explicit.

== Finite-Temperature Propagators: Scalar Field

== Finite-Temperature Propagators: Dirac Field

== Finite-Temperature Propagators: Gauge Field

== Sum-Integration and Useful Techniques
